Added line to bashscripts that stops the execution if any command fails

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,6 +3,9 @@
 # Usage: install 
 #
 
+# Stops execution if any command fails.
+set -eo pipefail
+
 createLinkSafely() {
     directory="$1"
     file="$2"
@@ -50,7 +53,7 @@ main() {
     # time bash starts, and load standard aliases and
     # shortcuts.
     if [[ -z $(grep ". ~/.standard_aliases" ~/.bashrc) ]]; then
-        cat ./scripts/append-to-bashrc >> ~/.bashrc
+        cat ./scripts/resources/append-to-bashrc >> ~/.bashrc
     fi
 
     echo "Run 'bash' for changes to take effect."
diff --git a/scripts/generate-shortcuts b/scripts/generate-shortcuts
--- a/scripts/generate-shortcuts
+++ b/scripts/generate-shortcuts
@@ -4,6 +4,10 @@
 # Runs parse-rc script, that parses ~/.standard_rc and generates
 # new ~/.standard_aliases/standard_shortcuts.
 
+# Stops execution if any command fails.
+set -eo pipefail
+#set -euo pipefail
+
 main() {
     scriptsDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
     existingCommands=$(
@@ -19,12 +23,12 @@ main() {
             "$HOME/.standard_aliases/standard_aliases" \
             "$existingCommands" \
             "$existingCompletions")
-    if [[ $? != 0 ]]; then
-        touch "$HOME"/.standard_rc
-        echo -n "Standard aliases: There is a problem in parse-rc.py " >&2
-        echo -n "script, so aliases were not loaded." >&2
-        exit 1
-    fi
+#    if [[ $? != 0 ]]; then
+#        touch "$HOME"/.standard_rc
+#        echo -n "Standard aliases: There is a problem in parse-rc.py " >&2
+#        echo -n "script, so aliases were not loaded." >&2
+#        exit 1
+#    fi
     echo "$shortcuts" > ~/.standard_aliases/standard_shortcuts
 }
 
diff --git a/scripts/update-project b/scripts/update-project
--- a/scripts/update-project
+++ b/scripts/update-project
@@ -3,14 +3,17 @@
 # Usage: update-projects
 # Generates stadard_shortcuts anew, if any file in project got changed.
 
+# Stops execution if any command fails.
+set -euo pipefail
+
 scriptsDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 
 isProjectsStandardRcUpToDate() {
     if [[ "$scriptsDir"/../standard_aliases \
         -nt "$scriptsDir"/../standard_rc ]]; then
-        return 1
+        echo "false"
     else
-        return 0
+        echo "true"
     fi
 }
 
@@ -27,19 +30,17 @@ areStandardShortcutsUpToDate() {
             -nt ~/.standard_aliases/standard_shortcuts ]] \
         || [[ "$scriptsDir"/parse-rc.py \
             -nt ~/.standard_aliases/standard_shortcuts ]]; then
-        return 1 
+        echo "false"
     else
-        return 0 
+        echo "true"
     fi
 }
 
 main() {
-    areStandardShortcutsUpToDate
-    if [[ $? -ne 0 ]]; then
+    if [[ $(areStandardShortcutsUpToDate) == "false" ]]; then
         "$scriptsDir"/generate-shortcuts
     fi
-    isProjectsStandardRcUpToDate
-    if [[ $? -ne 0 ]]; then
+    if [[ $(isProjectsStandardRcUpToDate) == "false" ]]; then
         newRc=$("$scriptsDir"/update-rc.py)
         echo "$newRc" >  "$scriptsDir"/../standard_rc
     fi
