Working on autocompletion for aliases

diff --git a/standard_aliases b/standard_aliases
--- a/standard_aliases
+++ b/standard_aliases
@@ -28,7 +28,7 @@ alias le='lessWithSensibleOptions'
 # input. First argument must be either 'true' or some other
 # value, true meaning that lessgets run with G option. G option
 # starts less at the end of the input (scrolled to the bottom).
-catOrLessWithOrWithoutG() {
+__catOrLessWithOrWithoutG() {
     if [[ "$#" -gt 1 ]]; then
         noOfLines=$(cat "$2" 2>/dev/null \
             | fold -w"$COLUMNS" \
@@ -60,14 +60,14 @@ catOrLessWithOrWithoutG() {
 # Runs cat or less, depending on number of lines in file or
 # input.
 catOrLess() {
-    catOrLessWithOrWithoutG 'false' "$@"
+    __catOrLessWithOrWithoutG 'false' "$@"
 }
 alias m='catOrLess'
 
 # Open cat or less +G (starts at the end of file), depending on
 # no of lines of file or input.
 catOrLessG() {
-    catOrLessWithOrWithoutG 'true' "$@"
+    __catOrLessWithOrWithoutG 'true' "$@"
 }
 
 # If file specified then runs cat or less, depending on no of
@@ -145,39 +145,32 @@ lsMedCat() {
         --time-style="+%b %d %Y %H:%M" "$@"
 }
 
-# CallslsWithSensibleOptions with: 
+# Calls lsWithSensibleOptions with: 
 #   * use long listing format. 
 lsLongCat() {
    lsWithSensibleOptions -l "$@"
 }
 
-# Functions that call aliases above, and pipe output to less.
-# They: 
-#   * override color option of ls to 'always' and 
-#   * pipe output to le with RAW-CONTROL-CHARS option.
-# This enables the transfer of colors from ls to less. They also
-# start less at end of file.
-
+# Calls lsShortCat and sends output to pager.
 lsShortLess() { 
     lsShortCat --color=always "$@" \
         | lessWithSensibleOptions --RAW-CONTROL-CHARS +G
 }
 
+# Calls lsMedCat and sends output to pager.
 lsMedLess() { 
     lsMedCat --color=always "$@" \
         | lessWithSensibleOptions --RAW-CONTROL-CHARS +G 
 }
 
+# Calls lsLongCat and sends output to pager.
 lsLongLess() { 
     lsLongCat --color=always "$@" \
         | lessWithSensibleOptions --RAW-CONTROL-CHARS +G 
 }
 
-# This functions decide weather they will call cat or less
-# version of the lsShort/Med/Long function. It depends on
-# whether the output of ls will fit on screen.
-
-# Calls ls (with a lot of options).
+# Calls lsShortCat if it's output fits on screen, otherwise
+# calls lsShortLess.
 lsShort() {
     noOfLines=$(
         lsShortCat "$@" 2> /dev/null \
@@ -190,8 +183,8 @@ lsShort() {
     fi
 }
 
-# Calls ls (with a lot of options) that uses shortened long
-# listing format.
+# Calls lsMedCat if it's output fits on screen, otherwise calls
+# lsMedLess.
 lsMed() {
     noOfLines=$(
         lsMedCat "$@" 2> /dev/null \
@@ -204,8 +197,8 @@ lsMed() {
     fi
 }
 
-# Calls ls (with a lot of options) that uses long listing
-# format.
+# Calls lsLongCat if it's output fits on screen, otherwise calls
+# lsLongLess.
 lsLong() {
     noOfLines=$(
         lsLongCat "$@" 2> /dev/null \
@@ -328,17 +321,35 @@ alias t='treeWithSensibleOptions'
 # CD #
 ######
 
-# Simplifies going up in directory hierarchy.
-alias cd..='cd ..'
-alias ..='cd ..'
-alias ,,='cd ..'
-alias ...='cd ../..'
-alias ,,,='cd ../..'
-alias ....='cd ..; cd ..; cd ..;'
-alias ,,,,='cd ..; cd ..; cd ..;'
-alias .....='cd ..; cd ..; cd ..; cd..'
-alias ......='cd ..; cd ..; cd ..; cd..; cd..'
-alias .......='cd ..; cd ..; cd ..; cd..; cd..; cd..'
+# Goes up in the directory hierarchy the specified number of
+# levels.
+goUpNoOfDirectories() {
+    if [[ "$#" -lt 1 ]]; then
+        # Needs parameter.
+        return 1
+    fi
+    re='^[1-9]$'
+    if ! [[ "$1" =~ $re ]] ; then
+        # Parameter is not a number or it's not the right size.
+        return 2
+    fi
+    i=1
+    while [[ "$i" -le "$1" ]]; do
+        cd ..
+        i=$(($i + 1))
+    done
+}
+
+alias cd..='goUpNoOfDirectories 1'
+alias ..='goUpNoOfDirectories 1'
+alias ,,='goUpNoOfDirectories 1'
+alias ...='goUpNoOfDirectories 2'
+alias ,,,='goUpNoOfDirectories 2'
+alias ....='goUpNoOfDirectories 3'
+alias ,,,,='goUpNoOfDirectories 3'
+alias .....='goUpNoOfDirectories 4'
+alias ......='goUpNoOfDirectories 5'
+alias .......='goUpNoOfDirectories 6'
 
 # Mounts ISO file and cd-s into it.
 mountIsoAndCdInto() {
@@ -355,6 +366,8 @@ alias cdiso='mountIsoAndCdInto'
 
 # Runs cp in interactive mode (asks before it overwrites
 # anything).
+alias cp='cp -iv'
+
 alias cp='cp -iv'
 
 # Runs mv in interactive mode (asks before it overwrites
@@ -410,9 +423,6 @@ alias switch='switchContentsOfFiles'
 # PWD #
 #######
 
-# Prints working directory.
-alias .='echo $PWD'
-
 # If no file specified, prints working directory, else full path
 # of the file.
 printPwdOrPath() {
@@ -466,7 +476,11 @@ alias ba='bash'
 # Prints location of specified command, or it's definition, if
 # it is an alias. Run this command if you are not sure what an
 # alias does!
-alias ty='type'
+typeWithPager() {
+    type "$@" | catOrLess
+}
+complete -F _command typeWithPager
+alias ty='typeWithPager'
 
 # Runs command as sudo.
 alias s='sudo'
@@ -523,6 +537,8 @@ alias da='date'
 makeWithPager() {
     make 2>&1 | lessWithSensibleOptions
 }
+. /usr/share/bash-completion/completions/make
+complete -F _make  makeWithPager
 alias make1='makeWithPager'
 alias ma='makeWithPager'
 
@@ -617,6 +633,7 @@ alias sub='runInBackground sublime_text'
 # As long as this line of text stays here and is not modified,
 # that long all the aliases and functions until next comment
 # will not get documented in README.md.
+# TODO check completions
 alias fdisk='sudo fdisk'
 alias updatedb='sudo updatedb'
 alias ifconfig='sudo ifconfig'
@@ -774,6 +791,7 @@ locateWithPager() {
     locate "$@" | grepWithPager "$@" 
 }
 alias locate1='locateWithPager'
+alias lo='locateWithPager'
 
 # Searches for files containing pattern in their names in
 # current and sub-directories.  Use filesystem regexes for
@@ -1561,3 +1579,109 @@ volumeDown2Db() {
 }
 alias zz='volumeDown2Db'
 
+
+###############
+# COMPLETIONS #
+###############
+
+#makeWithPager() {
+#    make 2>&1 | lessWithSensibleOptions
+#}
+#. /usr/share/bash-completion/completions/make
+#complete -F _make  makeWithPager
+#alias make1='makeWithPager'
+#alias ma='makeWithPager'
+
+# My take on automatic completion generation for aliases.
+# Sets automoatic completion function to same function as the first command in
+# alias has.
+# $1 - alias
+# $2 - first command of alias
+setCompletionFunctionForAlias() {
+    aliasName="$1"
+    commandName="$2"
+    #echo aliasName: "$aliasName" 
+    #echo commandName: "$commandName"
+    completionFunction=$(complete -p "$2" 2>/dev/null)
+    if [[ "$completionFunction" == "" ]]; then
+        return 1
+    fi
+    completionFunction=$(
+        echo "$completionFunction" \
+            | cut --delimiter=' ' --fields=3)
+    complete -F "$completionFunction" "$1"
+}
+eval "$(alias -p | sed -e 's/alias \([^=][^=]*\)='\''\([^ ][^ ]*\).*'\''/setCompletionFunctionForAlias \1 \2/')"
+
+# from stackowerflow:
+#eval "$(alias -p | sed -e 's/alias \([^=][^=]*\)='\''\([^ ][^ ]*\) *\(.*\)'\''/wrap_alias \1 \2 '\''\3'\'' /')"
+
+
+# Automatically add completion for all aliases to commands having completion functions
+function alias_completion {
+    local namespace="alias_completion"
+
+    # parse function based completion definitions, where capture group 2 => function and 3 => trigger
+    local compl_regex='complete( +[^ ]+)* -F ([^ ]+) ("[^"]+"|[^ ]+)'
+    # parse alias definitions, where capture group 1 => trigger, 2 => command, 3 => command arguments
+    local alias_regex="alias ([^=]+)='(\"[^\"]+\"|[^ ]+)(( +[^ ]+)*)'"
+
+    # create array of function completion triggers, keeping multi-word triggers together
+    eval "local completions=($(complete -p | sed -Ene "/$compl_regex/s//'\3'/p"))"
+    (( ${#completions[@]} == 0 )) && return 0
+
+    # create temporary file for wrapper functions and completions
+    rm -f "/tmp/${namespace}-*.tmp" # preliminary cleanup
+    local tmp_file; tmp_file="$(mktemp "/tmp/${namespace}-${RANDOM}XXX.tmp")" || return 1
+
+    local completion_loader; completion_loader="$(complete -p -D 2>/dev/null | sed -Ene 's/.* -F ([^ ]*).*/\1/p')"
+
+    # read in "<alias> '<aliased command>' '<command args>'" lines from defined aliases
+    local line; while read line; do
+        eval "local alias_tokens; alias_tokens=($line)" 2>/dev/null || continue # some alias arg patterns cause an eval parse error
+        local alias_name="${alias_tokens[0]}" alias_cmd="${alias_tokens[1]}" alias_args="${alias_tokens[2]# }"
+
+        # skip aliases to pipes, boolan control structures and other command lists
+        # (leveraging that eval errs out if $alias_args contains unquoted shell metacharacters)
+        eval "local alias_arg_words; alias_arg_words=($alias_args)" 2>/dev/null || continue
+        # avoid expanding wildcards
+        read -a alias_arg_words <<< "$alias_args"
+
+        # skip alias if there is no completion function triggered by the aliased command
+        if [[ ! " ${completions[*]} " =~ " $alias_cmd " ]]; then
+            if [[ -n "$completion_loader" ]]; then
+                # force loading of completions for the aliased command
+                eval "$completion_loader $alias_cmd"
+                # 124 means completion loader was successful
+                [[ $? -eq 124 ]] || continue
+                completions+=($alias_cmd)
+            else
+                continue
+            fi
+        fi
+        local new_completion="$(complete -p "$alias_cmd")"
+
+        # create a wrapper inserting the alias arguments if any
+        if [[ -n $alias_args ]]; then
+            local compl_func="${new_completion/#* -F /}"; compl_func="${compl_func%% *}"
+            # avoid recursive call loops by ignoring our own functions
+            if [[ "${compl_func#_$namespace::}" == $compl_func ]]; then
+                local compl_wrapper="_${namespace}::${alias_name}"
+                    echo "function $compl_wrapper {
+                        (( COMP_CWORD += ${#alias_arg_words[@]} ))
+                        COMP_WORDS=($alias_cmd $alias_args \${COMP_WORDS[@]:1})
+                        (( COMP_POINT -= \${#COMP_LINE} ))
+                        COMP_LINE=\${COMP_LINE/$alias_name/$alias_cmd $alias_args}
+                        (( COMP_POINT += \${#COMP_LINE} ))
+                        $compl_func
+                    }" >> "$tmp_file"
+                    new_completion="${new_completion/ -F $compl_func / -F $compl_wrapper }"
+            fi
+        fi
+
+        # replace completion trigger by alias
+        new_completion="${new_completion% *} $alias_name"
+        echo "$new_completion" >> "$tmp_file"
+    done < <(alias -p | sed -Ene "s/$alias_regex/\1 '\2' '\3'/p")
+    source "$tmp_file" && rm -f "$tmp_file"
+}; #alias_completion
